name: Backend services traffic generator

on:
  schedule:
    - cron: "*/30 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set Node.js 20.10.
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.x

      - name: Yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Yarn build
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command

      - name: Run app to generate fake API calls
        env:
          API_URL: ${{ vars.API_URL }}
        uses: borales/actions-yarn@v4
        with:
          cmd: start # will run `yarn start` command
